name: deu_pet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_card_swiper: ^7.0.2
  image_picker: ^1.1.2
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_core_web: ^2.21.0
  firebase_auth: ^5.5.0
  uuid: ^4.4.2
<<<<<<< HEAD
  http: ^1.1.0
  firebase_storage: 12.4.4

=======
  stream_chat_flutter: ^9.6.0
  dart_jsonwebtoken: ^3.1.1
  firebase_storage: 12.4.4


 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/search-pet.png
    - assets/icons/star-menu.png
    - assets/logo.png
    - assets/images/pet1.png
    - assets/images/pet2.png
    - assets/images/pet3.jpg
    - assets/images/pet4.jpg
    - assets/images/pet5.jpg
    - assets/images/pet6.jpg
    - assets/images/pet9.png
    - assets/images/pet10.jpeg
    - assets/images/pet12.jpeg
    - assets/images/pet-bob-2.png
    - assets/images/pet-bob-3.jpg
    - assets/images/pet-rex-2.jpg
    - assets/images/pet-rex-3.jpg
    - assets/images/pet-bella.jpg
    - assets/images/pet-bella-2.jpeg
    - assets/images/pet-bella-3.jpg
    - assets/images/person1.jpg
    - assets/images/person2.jpg
    - assets/images/person3.jpg
    - assets/images/deu_pet.png
    - assets/images/Background.png
