// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5B-EMRU73SJe6lgrLwwL__lhlQzACts4',
    appId: '1:383532033640:web:f907d1b112854257a9fddd',
    messagingSenderId: '383532033640',
    projectId: 'deupet-23e59',
    authDomain: 'deupet-23e59.firebaseapp.com',
    storageBucket: 'deupet-23e59.firebasestorage.app',
    measurementId: 'G-YSXQ7MMN69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-CxZQUi2EEHi-lZM7MTTMoAIRRJlpqA',
    appId: '1:383532033640:android:690b7ab196ca16eba9fddd',
    messagingSenderId: '383532033640',
    projectId: 'deupet-23e59',
    storageBucket: 'deupet-23e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSKhnaoEIDUUJIwYxNPZalWDNA8OBBYs4',
    appId: '1:383532033640:ios:f3dc6ea4cc0b16d7a9fddd',
    messagingSenderId: '383532033640',
    projectId: 'deupet-23e59',
    storageBucket: 'deupet-23e59.firebasestorage.app',
    iosBundleId: 'com.example.deuPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSKhnaoEIDUUJIwYxNPZalWDNA8OBBYs4',
    appId: '1:383532033640:ios:f3dc6ea4cc0b16d7a9fddd',
    messagingSenderId: '383532033640',
    projectId: 'deupet-23e59',
    storageBucket: 'deupet-23e59.firebasestorage.app',
    iosBundleId: 'com.example.deuPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5B-EMRU73SJe6lgrLwwL__lhlQzACts4',
    appId: '1:383532033640:web:327e84b215bff913a9fddd',
    messagingSenderId: '383532033640',
    projectId: 'deupet-23e59',
    authDomain: 'deupet-23e59.firebaseapp.com',
    storageBucket: 'deupet-23e59.firebasestorage.app',
    measurementId: 'G-V9K8S4D4S7',
  );
}
